<?php

/**
 * Implements hook_menu().
 */
function commerce_ads_menu() {
  $items = array();
  $items['admin/commerce/config/commerce_ads'] = array(
    'title' => 'ADS',
    'description' => 'Manage ADS Settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_ads_configure_form'),
    'access arguments' => array('administer ads'),
    'file' => 'includes/commerce_ads.admin.inc',
  );
  // Ads settings form.
  $items['admin/commerce/config/commerce_ads/configure'] = array(
    'title' => 'Configure',
    'description' => 'Manage your ADS Account feeds',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  // Product settings form.
  $items['admin/commerce/config/commerce_ads/products'] = array(
    'title' => 'Products',
    'description' => 'Product settings.',
    'type' => MENU_LOCAL_TASK,
    'weight' => 30,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_ads_product_configure_form'),
    'access arguments' => array('administer ads'),
    'file' => 'includes/commerce_ads.admin.inc',
  );
  // Order settings form.
  $items['admin/commerce/config/commerce_ads/orders'] = array(
    'title' => 'Orders',
    'description' => 'Order settings.',
    'type' => MENU_LOCAL_TASK,
    'weight' => 30,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_ads_order_configure_form'),
    'access arguments' => array('administer ads'),
    'file' => 'includes/commerce_ads.admin.inc',
  );
  // Shipping settings form.
  $items['admin/commerce/config/commerce_ads/shipping'] = array(
    'title' => 'Shipping',
    'description' => 'Shipping settings.',
    'type' => MENU_LOCAL_TASK,
    'weight' => 30,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_ads_shipping_configure_form'),
    'access arguments' => array('administer ads'),
    'file' => 'includes/commerce_ads.admin.inc',
  );

  return $items;
}